# Puerto del servidor para la API REST
server.port=8080

# Configuración obligatoria del motor de Base de Datos embebida H2
# NOTA: Cambia "carbajal_armando" por tu apellido y nombre en minúsculas tal como pide el examen
spring.datasource.url=jdbc:h2:mem:BD_carbajal_armando_T1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitación de la consola gráfica de H2 para auditoría de desarrollo
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
# Estrategia de persistencia: Crea y destruye las tablas limpias en cada reinicio
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Parámetros del Token JWT (OWASP A02 - Clave robusta de 256 bits)
jwt.secret=uqAiSolutionSecretKey2026ProgramacionSeguraDD281MustBe256bits
jwt.expiration=86400000

# Configuración de Orígenes Permitidos (CORS) para conectar con Next.js
cors.allowed.origins=http://localhost:3000